//! `weft html`, `weft react`, `weft solid` and their importers `weft import-html`,
//! `weft import-react`, `weft import-solid` (SPEC §9). Catalog and tokens resolve as for SwiftUI;
//! `--typescript` and `--source` fall back to the project's `export.<target>` settings, the output
//! directory to `export.<target>.outDir` or `import.<target>.outDir`, else standard output.
//! `weft html --data` falls back to `export.html.data`; without data the page is a template.
//! `weft css-tokens` writes the token stylesheet the components read, and `weft css-base` the base
//! rules they share with the static page, both to `export.css.outDir`.

use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Result, bail};
use weft_catalog::{PROJECT_FILE, appearance};
use weft_web::{
    BASE_CSS, Framework, HtmlOptions, ImportOptions, JsxOptions, import_html, import_jsx,
    to_html_with_data, to_jsx, tokens_css,
};

use crate::convert::{
    catalog, emit, finish_import, out_dir, project, sample_data, strict_document, switch, tokens,
};
use crate::swiftui::TokensArgs;
use crate::{DIAGNOSTICS, ProjectArgs, print, read};

/// The stylesheets' file names, which apps link to.
const CSS_TOKENS_FILE: &str = "weft-tokens.css";
const CSS_BASE_FILE: &str = "weft-base.css";

/// The `--weft-…` custom properties that generated React and SolidJS components read (SPEC §9),
/// following the system appearance when the tokens have one.
pub fn export_css(args: TokensArgs, out: &mut dyn Write) -> Result<u8> {
    // The project is found as for a document in the working directory.
    let (project, project_dir) = project(Path::new(PROJECT_FILE), args.project)?;
    let tokens = tokens(args.tokens.as_deref(), project.as_ref())?;
    let css = format!(
        "/* Generated by `weft css-tokens` from the project's design tokens. Regenerate it\n   instead of editing it: every component of the project reads its values. */\n{}",
        tokens_css(&tokens.tokens, appearance(&tokens.modifiers))
    );
    let dir = out_dir(
        args.out_dir,
        project.as_ref(),
        project_dir.as_deref(),
        "export",
        "css",
    );
    emit(
        &css,
        Path::new(CSS_TOKENS_FILE),
        dir,
        "css",
        args.force,
        out,
    )?;
    Ok(0)
}

/// The rules every web target shares (SPEC §9). They do not depend on the project: its tokens
/// reach them through the custom properties of `weft-tokens.css`.
pub fn export_css_base(
    project_args: ProjectArgs,
    out_dir_arg: Option<PathBuf>,
    force: bool,
    out: &mut dyn Write,
) -> Result<u8> {
    let (project, project_dir) = project(Path::new(PROJECT_FILE), project_args)?;
    let dir = out_dir(
        out_dir_arg,
        project.as_ref(),
        project_dir.as_deref(),
        "export",
        "css",
    );
    emit(BASE_CSS, Path::new(CSS_BASE_FILE), dir, "css", force, out)?;
    Ok(0)
}

#[derive(Clone, Copy)]
pub enum Target {
    Html,
    React,
    Solid,
    Lit,
}

impl Target {
    fn name(self) -> &'static str {
        match self {
            Self::Html => "html",
            Self::React => "react",
            Self::Solid => "solid",
            Self::Lit => "lit",
        }
    }
}

pub struct ExportArgs {
    pub force: bool,

    pub target: Target,
    pub file: PathBuf,
    pub catalog: Option<PathBuf>,
    pub tokens: Option<PathBuf>,
    pub project: ProjectArgs,
    pub out_dir: Option<PathBuf>,
    pub typescript: bool,
    pub javascript: bool,
    pub source: bool,
    pub no_source: bool,
    /// Sample data for the static page; the component targets take data at run time.
    pub data: Option<PathBuf>,
}

pub fn export(args: ExportArgs, out: &mut dyn Write) -> Result<u8> {
    let target = args.target.name();
    let (project, project_dir) = project(&args.file, args.project)?;
    let project = project.as_ref();
    let catalog = catalog(args.catalog.as_deref(), project)?;
    let Some(document) = strict_document(&args.file, &catalog)? else {
        return Ok(DIAGNOSTICS);
    };
    let source = switch(
        args.source,
        args.no_source,
        project,
        &["export", target, "source"],
    );
    let (text, extension) = match args.target {
        Target::Html => {
            let tokens = tokens(args.tokens.as_deref(), project)?;
            let data = sample_data(args.data, project, project_dir.as_deref(), target)?;
            let options = HtmlOptions {
                catalog: &catalog,
                tokens: &tokens.tokens,
                source,
                appearance: appearance(&tokens.modifiers),
            };
            match to_html_with_data(&document, &options, data.as_ref()) {
                Ok(html) => (html, "html"),
                // The tokens can still refuse a screen the catalog alone accepts.
                Err(invalid) => {
                    print(&args.file, &invalid.0, &mut std::io::stderr())?;
                    return Ok(DIAGNOSTICS);
                }
            }
        }
        Target::React | Target::Solid | Target::Lit => {
            // Lit has no TypeScript flavour; the generator refuses `--typescript` for it.
            let typescript = switch(
                args.typescript,
                args.javascript,
                project,
                &["export", target, "typescript"],
            );
            let json = serde_json::to_value(&document)?;
            let options = JsxOptions {
                catalog: &catalog,
                component_name: None,
                framework: match args.target {
                    Target::Solid => Framework::Solid,
                    Target::Lit => Framework::Lit,
                    _ => Framework::React,
                },
                typescript,
                source,
            };
            // The default component name is valid, so only an option Lit lacks can be refused.
            let code = to_jsx(&json, &options)?;
            let extension = match (args.target, typescript) {
                (Target::Lit, _) => "js",
                (_, true) => "tsx",
                _ => "jsx",
            };
            (code, extension)
        }
    };
    let dir = out_dir(
        args.out_dir,
        project,
        project_dir.as_deref(),
        "export",
        target,
    );
    emit(&text, &args.file, dir, extension, args.force, out)?;
    Ok(0)
}

pub struct ImportArgs {
    pub force: bool,

    pub target: Target,
    pub file: PathBuf,
    pub catalog: Option<PathBuf>,
    pub tokens: Option<PathBuf>,
    pub project: ProjectArgs,
    pub out_dir: Option<PathBuf>,
}

/// TypeScript by extension: `.tsx`, `.ts`, `.mts` and `.cts` hold types the JSX grammar refuses.
fn is_typescript(file: &Path) -> bool {
    file.extension().and_then(|e| e.to_str()).is_some_and(|e| {
        matches!(
            e.to_ascii_lowercase().as_str(),
            "tsx" | "ts" | "mts" | "cts"
        )
    })
}

pub fn import(args: ImportArgs, out: &mut dyn Write) -> Result<u8> {
    let (project, project_dir) = project(&args.file, args.project)?;
    let project = project.as_ref();
    let catalog = catalog(args.catalog.as_deref(), project)?;
    let tokens = tokens(args.tokens.as_deref(), project)?;
    let text = read(&args.file)?;
    let options = ImportOptions {
        catalog: &catalog,
        tokens: &tokens.tokens,
    };
    let result = match args.target {
        Target::Html => import_html(&text, &options),
        Target::React | Target::Solid => import_jsx(&text, is_typescript(&args.file), &options),
        // No Lit importer is wired to a command.
        Target::Lit => bail!("there is no importer for lit"),
    };
    let dir = out_dir(
        args.out_dir,
        project,
        project_dir.as_deref(),
        "import",
        args.target.name(),
    );
    finish_import(&args.file, &result, dir, args.force, out)
}
