// The XcodeBuildToolPlugin path: an Xcode project (generated by XcodeGen) whose app target applies
// the build tool plugin, built for iOS 17 and macOS 14 without Xcode's UI.
import { join } from "node:path";
import { afterAll, describe, expect, test } from "vitest";
import { hasXcodegen, run, skipReason, workspace } from "./helpers.ts";

describe.skipIf(skipReason || !hasXcodegen)("build tool plugin (Xcode project)", () => {
  const ws = workspace("XcodeSample");
  const derived = join(ws.root, "derived");
  afterAll(ws.cleanup);

  test("generates the project", () => {
    const generated = run("xcodegen", ["generate", "--quiet"], ws.sample);
    expect(generated.status, generated.output).toBe(0);
  });

  // -skipPackagePluginValidation is what Xcode's "Trust & Enable" button does; a headless build
  // has no one to press it.
  test.each([
    ["iOS 17", "generic/platform=iOS Simulator"],
    ["macOS 14", "generic/platform=macOS"],
  ])("builds for %s", { timeout: 900_000 }, (_name, destination) => {
    const built = run(
      "xcodebuild",
      [
        "-project",
        "XcodeSample.xcodeproj",
        "-scheme",
        "XcodeSample",
        "-destination",
        destination,
        "-derivedDataPath",
        derived,
        "-skipPackagePluginValidation",
        "ARCHS=arm64",
        "ONLY_ACTIVE_ARCH=YES",
        "build",
      ],
      ws.sample,
    );
    expect(built.status, built.output.slice(-4000)).toBe(0);
    // Xcode runs the command as a script phase and escapes the spaces of its name.
    expect(built.output).toMatch(/Weft:\\? generate\\? SwiftUI\\? from\\? login\.weft/);
    expect(built.output).toContain("BUILD SUCCEEDED");
  });
});
