// Grammars and fixed vocabulary from SPEC §2–§4, for packages that build or read documents
// themselves (the importer, the renderer). The core's own checks live in
// crates/weft-core/src/rules.rs; these must say the same.
export const ID = /^[A-Za-z][A-Za-z0-9_-]*$/;
export const ACTION = /^[a-z][A-Za-z0-9]*(?:\.[a-z][A-Za-z0-9]*)*$/;
export const LOOP_VARIABLE = /^[a-z][A-Za-z0-9]*$/;
const SEGMENT = "(?:[A-Za-z_][A-Za-z0-9_]*|0|[1-9][0-9]*)";
export const BINDING = new RegExp(
  `^\\$(?:(?:\\.${SEGMENT})+|[A-Za-z_][A-Za-z0-9_]*(?:\\.${SEGMENT})*)$`,
);
export const TOKEN = /^[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)*$/;
/** A reference written after other text in one value, e.g. `Hello {$.name}` (SPEC §2.1). */
export const EMBEDDED_REFERENCE = /\{!?\$|\{token\./;
/** Characters XML 1.0 cannot carry at all, not even as character references. */
export const NON_XML_CHAR = /[^\t\n\r\x20-\uD7FF\uE000-\uFFFD\u{10000}-\u{10FFFF}]/u;

/** Non-abstract roles of WAI-ARIA 1.2, https://www.w3.org/TR/wai-aria-1.2/#role_definitions */
export const ARIA_ROLES: readonly string[] = [
  "alert",
  "alertdialog",
  "application",
  "article",
  "banner",
  "blockquote",
  "button",
  "caption",
  "cell",
  "checkbox",
  "code",
  "columnheader",
  "combobox",
  "complementary",
  "contentinfo",
  "definition",
  "deletion",
  "dialog",
  "document",
  "emphasis",
  "feed",
  "figure",
  "form",
  "generic",
  "grid",
  "gridcell",
  "group",
  "heading",
  "img",
  "insertion",
  "link",
  "list",
  "listbox",
  "listitem",
  "log",
  "main",
  "marquee",
  "math",
  "menu",
  "menubar",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "meter",
  "navigation",
  "none",
  "note",
  "option",
  "paragraph",
  "presentation",
  "progressbar",
  "radio",
  "radiogroup",
  "region",
  "row",
  "rowgroup",
  "rowheader",
  "scrollbar",
  "search",
  "searchbox",
  "separator",
  "slider",
  "spinbutton",
  "status",
  "strong",
  "subscript",
  "superscript",
  "switch",
  "tab",
  "table",
  "tablist",
  "tabpanel",
  "term",
  "textbox",
  "time",
  "timer",
  "toolbar",
  "tooltip",
  "tree",
  "treegrid",
  "treeitem",
];
