//! Design tokens as Swift (SPEC §9): a struct of nested groups named after the token paths, so
//! `{token.space.md}` reads `theme.space.md`. A project shares one `WeftTokens` struct holding
//! every token it can express (`generate_tokens`); a screen generated without one carries its own
//! `<Screen>Theme` with the tokens it references, so the file stays self-contained.

use std::collections::BTreeMap;

use indexmap::IndexMap;
use serde_json::Value as Json;
use weft_catalog::Token;

use crate::Unsupported;
use crate::swift::{self, number_literal, string_literal};

/// The type of the shared tokens; screens that use it declare `var theme = WeftTokens()`.
pub const TOKENS_TYPE: &str = "WeftTokens";

/// The file name `generate_tokens` output is written to.
pub const TOKENS_FILE: &str = "WeftTokens.swift";

/// CSS `rem` against the browser default; SwiftUI points match CSS pixels.
const POINTS_PER_REM: f64 = 16.0;

/// A token as a stored property: its Swift type and initial value.
struct Leaf {
    ty: &'static str,
    value: String,
}

#[derive(Default)]
struct Group {
    leaves: BTreeMap<String, Leaf>,
    groups: BTreeMap<String, Group>,
}

/// `theme.space.md` for the token path `space.md`.
pub fn token_expr(path: &str) -> String {
    let mut out = String::from("theme");
    for segment in path.split('.') {
        out.push('.');
        out.push_str(&swift::token_member(segment));
    }
    out
}

/// The whole token set as `WeftTokens.swift`, and the tokens left out because SwiftUI has no
/// form for their type or value.
pub fn generate_tokens(tokens: &IndexMap<String, Token>) -> (String, Vec<Unsupported>) {
    let mut skipped = vec![];
    let lines = tokens_struct(
        TOKENS_TYPE,
        tokens.keys().map(String::as_str),
        tokens,
        &mut skipped,
    );
    let mut out = vec![
        "// Generated by `weft swiftui-tokens` from the project's design tokens. Regenerate it"
            .to_owned(),
        "// instead of editing it: every screen of the project reads its values.".to_owned(),
        String::new(),
        "import SwiftUI".to_owned(),
        String::new(),
        "/// The project's design tokens: colours, sizes in points, fonts and timing.".to_owned(),
    ];
    out.extend(lines);
    let mut text = out.join("\n");
    text.push('\n');
    (text, skipped)
}

/// Whether a screen can refer to `path` in the shared tokens: the reason when it cannot.
pub fn check_token(path: &str, tokens: &IndexMap<String, Token>) -> Option<Unsupported> {
    let token = tokens.get(path);
    let problem = match token.map(|t| swift_value(t, tokens)) {
        None => "the token is not in the token set".to_owned(),
        Some(Err(message)) => message,
        Some(Ok(_)) => return None,
    };
    Some(Unsupported::new(format!("{{token.{path}}}"), problem))
}

/// The lines of a struct named `name` holding the tokens at `paths`, indented by the caller.
/// A token that cannot be expressed is reported in `problems` and left out.
pub fn tokens_struct<'p>(
    name: &str,
    paths: impl IntoIterator<Item = &'p str>,
    tokens: &IndexMap<String, Token>,
    problems: &mut Vec<Unsupported>,
) -> Vec<String> {
    let mut root = Group::default();
    for path in paths {
        if let Some(problem) = check_token(path, tokens) {
            problems.push(problem);
            continue;
        }
        let Some(Ok(leaf)) = tokens.get(path).map(|t| swift_value(t, tokens)) else {
            continue;
        };
        let segments: Vec<&str> = path.split('.').collect();
        let Some((last, groups)) = segments.split_last() else {
            continue;
        };
        let mut group = &mut root;
        for segment in groups {
            group = group.groups.entry((*segment).to_owned()).or_default();
        }
        group.leaves.insert((*last).to_owned(), leaf);
    }
    let mut lines = vec![];
    print_group(name, &root, &mut lines, "", "", problems);
    lines
}

fn print_group(
    name: &str,
    group: &Group,
    out: &mut Vec<String>,
    indent: &str,
    path: &str,
    problems: &mut Vec<Unsupported>,
) {
    out.push(format!("{indent}struct {name}: Sendable {{"));
    let inner = format!("{indent}    ");
    let mut types: Vec<(String, &str, &Group)> = vec![];
    for (segment, group) in &group.groups {
        if group.leaves.is_empty() && group.groups.is_empty() {
            continue;
        }
        let type_name = group_type_name(segment, types.iter().map(|(t, _, _)| t.as_str()));
        out.push(format!(
            "{inner}var {} = {type_name}()",
            swift::token_member(segment)
        ));
        types.push((type_name, segment, group));
    }
    let full = |segment: &str| {
        if path.is_empty() {
            segment.to_owned()
        } else {
            format!("{path}.{segment}")
        }
    };
    for (segment, leaf) in &group.leaves {
        if group.groups.contains_key(segment) {
            problems.push(Unsupported::new(
                format!("{{token.{}}}", full(segment)),
                "a token path is both a token and a group of the referenced tokens",
            ));
            continue;
        }
        if segment == "_root" && group.leaves.contains_key("$root") {
            problems.push(Unsupported::new(
                format!("{{token.{}}}", full(segment)),
                "`_root` is the Swift name of the group's `$root` token",
            ));
            continue;
        }
        out.push(format!(
            "{inner}var {}: {} = {}",
            swift::token_member(segment),
            leaf.ty,
            leaf.value
        ));
    }
    for (type_name, segment, group) in types {
        out.push(String::new());
        print_group(&type_name, group, out, &inner, &full(segment), problems);
    }
    out.push(format!("{indent}}}"));
}

/// `space` → `SpaceTokens`. The suffix keeps a group named `color` or `font` from shadowing the
/// SwiftUI type its tokens are declared with.
fn group_type_name<'a>(segment: &str, taken: impl Iterator<Item = &'a str> + Clone) -> String {
    let mut chars = segment.chars();
    let stem = match chars.next() {
        Some(first) if first.is_ascii_alphabetic() => {
            let candidate: String = first.to_uppercase().chain(chars).collect();
            if swift::is_plain_identifier(&candidate) {
                candidate
            } else {
                "Group".to_owned()
            }
        }
        _ => "Group".to_owned(),
    };
    let base = format!("{stem}Tokens");
    let mut name = base.clone();
    let mut n = 2;
    while taken.clone().any(|t| t == name) {
        name = format!("{base}{n}");
        n += 1;
    }
    name
}

// ---- Values ----

/// The Swift type and value of a token, or why SwiftUI has none.
fn swift_value(token: &Token, tokens: &IndexMap<String, Token>) -> Result<Leaf, String> {
    let v = &token.value;
    let leaf = match token.kind.as_str() {
        "color" => color(v).map(|value| Leaf { ty: "Color", value }),
        "dimension" => points(v).map(|n| Leaf {
            ty: "CGFloat",
            value: number_literal(n),
        }),
        "number" => finite(v).map(|n| Leaf {
            ty: "Double",
            value: number_literal(n),
        }),
        "fontFamily" => families(v).map(|names| Leaf {
            ty: "[String]",
            value: format!("[{}]", names.join(", ")),
        }),
        "fontWeight" => weight(v).map(|w| Leaf {
            ty: "Font.Weight",
            value: format!(".{w}"),
        }),
        "duration" => seconds(v).map(|s| Leaf {
            ty: "Double",
            value: number_literal(s),
        }),
        "cubicBezier" => bezier(v).map(|value| Leaf {
            ty: "UnitCurve",
            value,
        }),
        "typography" => font(v, tokens).map(|value| Leaf { ty: "Font", value }),
        other => return Err(format!("SwiftUI has no form for `{other}` tokens")),
    };
    leaf.ok_or_else(|| {
        format!(
            "the `{}` token's value has no SwiftUI form (README: \"Tokens\")",
            token.kind
        )
    })
}

fn finite(v: &Json) -> Option<f64> {
    v.as_f64().filter(|n| n.is_finite())
}

fn points(v: &Json) -> Option<f64> {
    let number = finite(v.get("value")?)?;
    match v.get("unit")?.as_str()? {
        "px" => Some(number),
        "rem" => Some(number * POINTS_PER_REM),
        _ => None,
    }
}

/// Four decimals keep every 8-bit channel exact after rounding.
fn channel(n: f64) -> String {
    number_literal((n * 10_000.0).round() / 10_000.0)
}

/// DTCG 2025.10 colours are objects: components in a colour space SwiftUI has, else the `hex`
/// fallback the format requires for any other space.
fn color(v: &Json) -> Option<String> {
    // The string form of earlier DTCG drafts is still common (the example project uses it).
    if let Some(s) = v.as_str() {
        let (values, alpha) = hex(s)?;
        return Some(rgb(".sRGB", &values, alpha));
    }
    let space = match v.get("colorSpace")?.as_str()? {
        "srgb" => Some(".sRGB"),
        "srgb-linear" => Some(".sRGBLinear"),
        "display-p3" => Some(".displayP3"),
        _ => None,
    };
    let alpha = match v.get("alpha") {
        None => 1.0,
        Some(a) => finite(a).filter(|a| (0.0..=1.0).contains(a))?,
    };
    let components = v.get("components").and_then(Json::as_array);
    if let (Some(space), Some(components)) = (space, components)
        && components.len() == 3
    {
        // `none` is a missing component, which reads as zero.
        let values: Option<Vec<f64>> = components
            .iter()
            .map(|c| if c == "none" { Some(0.0) } else { finite(c) })
            .collect();
        if let Some(values) = values {
            return Some(rgb(space, &values, alpha));
        }
    }
    let (values, hex_alpha) = hex(v.get("hex")?.as_str()?)?;
    let alpha = if v.get("alpha").is_some() {
        alpha
    } else {
        hex_alpha
    };
    Some(rgb(".sRGB", &values, alpha))
}

fn rgb(space: &str, c: &[f64], alpha: f64) -> String {
    format!(
        "Color({space}, red: {}, green: {}, blue: {}, opacity: {})",
        channel(c[0]),
        channel(c[1]),
        channel(c[2]),
        channel(alpha)
    )
}

/// `#rgb`, `#rgba`, `#rrggbb` or `#rrggbbaa` as channels from 0 to 1, and the alpha.
fn hex(text: &str) -> Option<(Vec<f64>, f64)> {
    let digits = text.strip_prefix('#')?;
    if !digits.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    let pairs: Vec<String> = match digits.len() {
        3 | 4 => digits.chars().map(|c| format!("{c}{c}")).collect(),
        6 | 8 => digits
            .as_bytes()
            .chunks(2)
            .map(|p| String::from_utf8_lossy(p).into_owned())
            .collect(),
        _ => return None,
    };
    let values: Vec<f64> = pairs
        .iter()
        .map(|p| u8::from_str_radix(p, 16).map(|n| f64::from(n) / 255.0))
        .collect::<Result<_, _>>()
        .ok()?;
    let alpha = values.get(3).copied().unwrap_or(1.0);
    Some((values[..3].to_vec(), alpha))
}

/// A family or a list of fallbacks, as Swift string literals.
fn families(v: &Json) -> Option<Vec<String>> {
    match v {
        Json::String(s) if !s.is_empty() => Some(vec![string_literal(s)]),
        Json::Array(list) if !list.is_empty() => list
            .iter()
            .map(|f| f.as_str().filter(|s| !s.is_empty()).map(string_literal))
            .collect(),
        _ => None,
    }
}

/// The `Font.Weight` for a DTCG weight: a number from 1 to 1000 or one of its names. SwiftUI's
/// nine weights stand for the hundreds, from `ultraLight` (100) to `black` (900).
fn weight(v: &Json) -> Option<&'static str> {
    const WEIGHTS: [&str; 9] = [
        "ultraLight",
        "thin",
        "light",
        "regular",
        "medium",
        "semibold",
        "bold",
        "heavy",
        "black",
    ];
    let number = match v {
        Json::String(name) => match name.as_str() {
            "thin" | "hairline" => 100.0,
            "extra-light" | "ultra-light" => 200.0,
            "light" => 300.0,
            "normal" | "regular" | "book" => 400.0,
            "medium" => 500.0,
            "semi-bold" | "demi-bold" => 600.0,
            "bold" => 700.0,
            "extra-bold" | "ultra-bold" => 800.0,
            "black" | "heavy" | "extra-black" | "ultra-black" => 900.0,
            _ => return None,
        },
        other => finite(other).filter(|n| (1.0..=1000.0).contains(n))?,
    };
    let step = (number / 100.0).round().clamp(1.0, 9.0) as usize;
    Some(WEIGHTS[step - 1])
}

fn seconds(v: &Json) -> Option<f64> {
    let number = finite(v.get("value")?)?;
    match v.get("unit")?.as_str()? {
        "ms" => Some(number / 1000.0),
        "s" => Some(number),
        _ => None,
    }
}

fn bezier(v: &Json) -> Option<String> {
    let p: Vec<f64> = v
        .as_array()
        .filter(|a| a.len() == 4)?
        .iter()
        .map(finite)
        .collect::<Option<_>>()?;
    Some(format!(
        ".bezier(startControlPoint: UnitPoint(x: {}, y: {}), endControlPoint: UnitPoint(x: {}, y: {}))",
        number_literal(p[0]),
        number_literal(p[1]),
        number_literal(p[2]),
        number_literal(p[3])
    ))
}

/// The CSS generic families SwiftUI draws with the system font, and the design each one means.
const GENERIC_FAMILIES: &[(&str, Option<&str>)] = &[
    ("system-ui", None),
    ("-apple-system", None),
    ("ui-sans-serif", None),
    ("sans-serif", None),
    ("ui-serif", Some(".serif")),
    ("serif", Some(".serif")),
    ("ui-monospace", Some(".monospaced")),
    ("monospace", Some(".monospaced")),
    ("ui-rounded", Some(".rounded")),
];

/// A typography token as a `Font`. Letter spacing and line height are not part of a SwiftUI
/// font, so they are left out (README: "Tokens").
fn font(v: &Json, tokens: &IndexMap<String, Token>) -> Option<String> {
    // The loader resolves whole-value aliases only; a typography part may still name a token.
    let part = |key: &str| -> Option<Json> {
        let value = v.get(key)?;
        let alias = value
            .as_str()
            .and_then(|s| s.strip_prefix('{'))
            .and_then(|s| s.strip_suffix('}'));
        match alias {
            Some(path) => tokens.get(path).map(|t| t.value.clone()),
            None => Some(value.clone()),
        }
    };
    let size = number_literal(points(&part("fontSize")?)?);
    let weight = match part("fontWeight") {
        Some(w) => Some(weight(&w)?),
        None => None,
    };
    let family = part("fontFamily")?;
    let first = match &family {
        Json::String(s) => s.clone(),
        Json::Array(list) => list.first()?.as_str()?.to_owned(),
        _ => return None,
    };
    if first.is_empty() {
        return None;
    }
    if let Some((_, design)) = GENERIC_FAMILIES.iter().find(|(name, _)| *name == first) {
        let mut args = vec![format!("size: {size}")];
        if let Some(w) = weight {
            args.push(format!("weight: .{w}"));
        }
        if let Some(d) = design {
            args.push(format!("design: {d}"));
        }
        return Some(format!(".system({})", args.join(", ")));
    }
    let custom = format!(".custom({}, size: {size})", string_literal(&first));
    Some(match weight {
        Some(w) => format!("{custom}.weight(.{w})"),
        None => custom,
    })
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn value(kind: &str, value: Json) -> Result<String, String> {
        let token = Token {
            kind: kind.to_owned(),
            value,
        };
        swift_value(&token, &IndexMap::new()).map(|l| format!("{}: {}", l.ty, l.value))
    }

    #[test]
    fn colours_use_their_space_or_fall_back_to_hex() {
        assert_eq!(
            value(
                "color",
                json!({ "colorSpace": "display-p3", "components": [1, 0.5, "none"], "alpha": 0.5 })
            ),
            Ok("Color: Color(.displayP3, red: 1, green: 0.5, blue: 0, opacity: 0.5)".to_owned())
        );
        assert_eq!(
            value(
                "color",
                json!({ "colorSpace": "oklch", "components": [0.5, 0.1, 30], "hex": "#ff000080" })
            ),
            Ok("Color: Color(.sRGB, red: 1, green: 0, blue: 0, opacity: 0.502)".to_owned())
        );
        assert_eq!(
            value("color", json!("#d97706")),
            Ok(
                "Color: Color(.sRGB, red: 0.851, green: 0.4667, blue: 0.0235, opacity: 1)"
                    .to_owned()
            )
        );
        assert!(value("color", json!("orange")).is_err());
    }

    #[test]
    fn other_types_map_to_their_swiftui_forms() {
        assert_eq!(
            value("dimension", json!({ "value": 1.5, "unit": "rem" })),
            Ok("CGFloat: 24".to_owned())
        );
        assert_eq!(
            value("duration", json!({ "value": 250, "unit": "ms" })),
            Ok("Double: 0.25".to_owned())
        );
        assert_eq!(
            value("fontWeight", json!("semi-bold")),
            Ok("Font.Weight: .semibold".to_owned())
        );
        assert_eq!(
            value("fontWeight", json!(350)),
            Ok("Font.Weight: .regular".to_owned())
        );
        assert_eq!(
            value("fontFamily", json!(["Inter", "system-ui"])),
            Ok("[String]: [\"Inter\", \"system-ui\"]".to_owned())
        );
        assert_eq!(
            value(
                "typography",
                json!({ "fontFamily": "ui-monospace", "fontSize": { "value": 12, "unit": "px" }, "fontWeight": 700 })
            ),
            Ok("Font: .system(size: 12, weight: .bold, design: .monospaced)".to_owned())
        );
        assert!(value("shadow", json!({})).is_err());
        assert!(value("dimension", json!({ "value": 1, "unit": "em" })).is_err());
    }

    #[test]
    fn root_tokens_get_a_swift_name() {
        assert_eq!(token_expr("color.blue.$root"), "theme.color.blue._root");
    }
}
